global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: vmware-metrics-demo
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets: ['vmware-metrics-demo:80']
